### ISSUE TITLE
2 Bravia TV's homekit sources

### ISSUE THREAD

**Issue by realm360** [custom-components/media_player.braviatv_psk#19]
Thanks for the great work!
I got 2 bravia tv's. in HA both work perfect.
In homekit only 1 tv gives me a source list ' HD' and - HDMI setting.
The other tv (in homekit) only gives On/Off. 
Booted several times HA and one time both where good. (bug?)

**Comment by gerard33** [comment]
Thanks!
I think this is related to Homekit. Did you have on of the TVs added to Homekit before the support for Homekit `device_class: tv` was [added](https://github.com/custom-components/media_player.braviatv_psk/releases/tag/0.3.0)?
Because then this is the issue -> https://www.home-assistant.io/integrations/homekit/#my-media-player-is-not-showing-up-as-a-television-accessory

**Comment by gerard33** [comment]
Closing this one as there is no reaction. Feel free to re-open if needed.
